---
name: Test

on:    
  workflow_dispatch:
    inputs:
      version:
        description: Chart version
        required: true
      
jobs:
  build:
    name: Chart release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          pwd
          sed 's/\(version:\).*/\1 '$VERSION'/' -i charts/documentserver/Chart.yaml
          cat charts/documentserver/Chart.yaml
        env:
          VERSION: ${{ github.event.inputs.version }}