---
name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Chart release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          wget https://download.onlyoffice.com/charts/stable/index.yaml -P /tmp
          LATEST_VERSION=$(awk '/documentserver:/{f=1};f{print}' /tmp/index.yaml | awk '/version:/ {print $2;}' | head -1)
          NEW_VERSION=$(awk '/version:/' Chart.yaml)
          echo $LATEST_VERSION
          echo $NEW_VERSION
