---
name: Test

on:    
  workflow_dispatch:
    inputs:
      version:
        description: Chart version
        required: true
      
jobs:
  build:
    name: Chart release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          sed -i 's/version:*/version:$VERSION/' charts/documentserver/Chart.yaml
        env:
          VERSION: ${{ github.event.inputs.version }}