---
name: Release Chart on S3 repo

on:    
  workflow_dispatch
      
jobs:
  build:
    name: Chart release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          ls
